config/routes.rb
Rails.application.routes.draw do
  resources :missions
  resources :users do
    get :mission, :on => :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  root "missions#index"

  match '/admin',  to: 'users#index', via: :get, as: "admin"
  match '/signup',  to: 'users#new', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :missions, :dependent => :delete_all
  has_many :tags, :dependent => :delete_all
  has_secure_password

  # 為了可以使用 current_user.role / User.roles.values / current_user.admin? 這些方法 改成 enum
  enum role: { admin: 'admin', user: 'user' }

  # 用在使用者更新資料的時候設定為 true，否則要一直 key 密碼很麻煩
  attr_accessor :skip_password_validation

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token 
  before_destroy :check_last_admin

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, unless: :skip_password_validation
  validates :password_confirmation, presence: true, unless: :skip_password_validation

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def check_last_admin
    if User.where(role: "admin").count == 1
      errors[:base] << I18n.t("user.admin_only_one")
      throw :abort
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin, only: [:index, :edit, :update, :destroy]
  before_action :find_user, only: [:edit, :update, :show, :destroy, :mission]

  def index
    # 晚點需要用分頁處理
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.skip_password_validation = true
    if @user.update(user_params)
      redirect_to admin_path, notice: t("notice.update_success")
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @user.destroy
      redirect_to admin_path, notice: t("notice.delete_success")
    else
      redirect_to admin_path, notice: t("notice.delete_fail")
    end
  end

  def mission
    @missions = @user.missions
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def check_admin
    (redirect_to root_path, notice: t("user.role_must_be_admin")) unless current_user.role == "admin"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<div>
  <%= form_for user do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit t("missions.submit") %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1> <%= t("user.edit_user") %> </h1>

<div>
  <%= form_for @user do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :role %>
    <%= f.select(:role, User.roles.values) %>

    <%= f.submit t("missions.submit") %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1><%= t("user.user_list") %></h1>
<%= link_to t("user.create_user"), signup_path, class: "btn btn-success" %>
<%= link_to t("user.back_to_missions"), root_path, class: "btn btn-success" %>
<table class="table">
  <thead>
    <tr>
      <td> <%= t("user.name") %> </td>
      <td> <%= t("user.email") %> </td>
      <td> <%= t("user.role") %> </td>
      <td> <%= t("user.mission_count") %> </td>
      <td> <%= t("missions.action") %> </td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td> <%= user.name %> </td>
        <td> <%= user.email %> </td>
        <td> <%= user.role %> </td>
        <td> <%= link_to user.missions.count, mission_user_path(id: user.id) %>  </td>
        <td>
          <%= link_to t("missions.edit"), edit_user_path(id: user.id), class: "btn btn-success" %> 
          <%= link_to t("missions.delete"), user_path(id: user.id), method: "delete", data: { confirm: t("missions.confirm_delete") }, class: "btn btn-danger" %> 
        </td>
      </tr>
    <% end %>
  </tbody>



</table>

app/views/users/mission.html.erb
<h1> <%= t("missions.mission_list") %> </h1>

<%= t("user.user") %>： <%= @user.name %>

<div>
  <%= link_to t("user.back_to_admin"), admin_path, class: "btn btn-success" %>
</div>

<table class="table">
  <thead>
    <tr>
      <td> <%= t("missions.mission_name") %> </td>
      <td> <%= t("missions.status") %> </td>
      <td> <%= t("missions.start_time") %> </td>
      <td> <%= t("missions.end_time") %> </td>
      <td> <%= t("missions.priority") %> </td>
      <td> <%= t("missions.category") %> </td>
    </tr>
  </thead>
  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.title %> </td>
        <td> <%= mission_status(mission) %> </td>
        <td> <%= mission.start_time %> </td>
        <td> <%= mission.end_time %> </td>
        <td> <%= mission_enum_name(mission, :priority) %> </td>
        <td> <%= mission_enum_name(mission, :category)  %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1> <%= t("user.sign_up") %> </h1>

<%= render "user_form", user: @user %>

app/views/users/show.html.erb
<h1> <%= t("user.personal_info") %> </h1>
<div>
  <%= t("user.name") %>：<%= @user.name %>
</div>
<div>
  <%= t("user.email") %>：<%= @user.email %>
</div>