config/routes.rb
Rails.application.routes.draw do
  resources :missions
  resources :users do
    get :mission, :on => :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  root "missions#index"

  match '/admin',  to: 'users#index', via: :get, as: "admin"
  match '/signup',  to: 'users#new', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/mission.rb
class Mission < ApplicationRecord
  paginates_per 25

  scope :overdue, -> { where("end_time < ?", Time.now) }
  scope :close_to_due, -> { where("end_time > ? and end_time < ?", Time.now, Time.now + 12.hours) }

  include AASM
  belongs_to :user
  has_many :mission_tag_logs
  has_many :tags, through: :mission_tag_logs
  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true

  enum priority: [ :urgent, :common, :low ]
  enum category: [ :company, :home ]

  validates :title, presence: true
  validates :priority, presence: true
  validates :category, presence: true
  validates :start_time, presence: true

  aasm column: 'status' do
    state :pending, initial: true
    state :handling, :complete

    event :handle do
      transitions from: :pending, to: :handling
    end

    event :finish do
      transitions from: :handling, to: :complete
    end
  end

  def tags_attributes=(tags_hash)
    # tag_ids = self.tags.ids # 原本有的tag ids
    new_tags = []
    
    tags_hash.each do |_, tag_hash|
      next if tag_hash['name'].blank? # 去除沒有tag name的
      
      tag = user.tags.find_by(name: tag_hash['name'])
      if tag
        new_tags << tag
      elsif tag_hash['id']
        tag_hash.delete('id')
        new_tags << user.tags.build(tag_hash)
      else
        new_tags << user.tags.build(tag_hash)
      end
    end
    self.tags = new_tags
  end

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :find_mission, only: [:edit, :update, :destroy]
  before_action :check_login
  before_action :mission_remind, only: [:index]

  def index
    @q = Mission.ransack(params[:q])
    @missions = @q.result.includes(:tags).where(user_id: current_user.id).order("#{order_params} desc").page(params[:page])
  end

  def new
    @mission = Mission.new
    5.times do
      @mission.tags.build
    end
  end

  def create
    @mission = current_user.missions.new # 先new出來，user_id才會出來
    @mission.attributes = mission_params
    if @mission.save
      redirect_to root_path, notice: t("notice.create_mission_success")
    else
      render :new
    end
  end

  def edit
    # 把 tag form 補到五個
    (5 - @mission.tags.count).times do
      @mission.tags.build
    end
  end

  def update
    if @mission.update(mission_params)
      redirect_to root_path, notice: t("notice.update_success")
    else
      render :edit
    end
  end

  def destroy
    if @mission.destroy
      redirect_to root_path, notice: t("notice.delete_success")
    else
      redirect_to root_path, notice: t("notice.delete_fail")
    end
  end


  private
  def find_mission
    @mission = Mission.find_by(id: params[:id])
  end

  def mission_params
    params.require(:mission).permit(:title, :priority, :category, :start_time, :end_time, :user_id, tags_attributes: [:id, :name, :_destroy])
  end

  # def mission_and_tag_params
  #   new_params = mission_params.tap do |mp|
  #     mp[:tags_attributes] = mp[:tags_attributes].to_h.reduce({}) do |rs, hash|
  #       v = hash[1] # 拿 value 值["0", {"name"=>"aaa"}]
  #       if v["name"] == ""  # 如果名字是空白不增加
  #       else
  #         hash[1] =  hash[1].merge('user_id' => current_user.id)

  #         exist_tag = current_user.tags.find_by(name: v["name"])
  #         hash[1] =  hash[1].merge('id' => exist_tag.id)if exist_tag 

  #         rs = rs.merge(hash[0] => hash[1])
  #       end
  #       rs
  #     end
  #   end
  #   new_params
  # end

  def order_params
    whitelist = %w[created_at end_time priority]
    if params[:order_by].in?(whitelist)
      params[:order_by]
    else
      "created_at"
    end 
  end

  def check_login
    redirect_to signin_path unless signed_in?
  end

  def mission_remind
    @overdue_missions = current_user.missions.overdue.pluck('title').join(",")
    flash[:overdue] = "#{@overdue_missions} is overdue!"  if !@overdue_missions.blank?
    @urgent_missions = current_user.missions.close_to_due.pluck('title').join(",")
    flash[:urgent] = "#{@urgent_missions} is urgent!"  if !@urgent_missions.blank?
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
  def priority_selection
    [[t("missions.urgent"), 'urgent'], [t("missions.common"), "common"], [t("missions.low"), "low"]]
  end

  def category_selection
    [[t("missions.public"), "company"], [t("missions.home"), "home"]]
  end
end

app/views/missions/_mission_form.html.erb
<%= form_for mission do |f| %>
  <% if mission.errors.any? %>
    <% mission.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <div class= "container">
    <div class= "form-group">
      <%= f.label :title, t("missions.mission_name") %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class= "form-group">
      <%= f.label :priority, t("missions.priority") %>
      <%= f.select(:priority, priority_selection, {}, {class: "form-control"}) %>
    </div>
    <div class= "form-group">
      <%= f.label :category, t("missions.category") %>
      <%= f.select(:category, category_selection, {}, {class: "form-control"}) %>
    </div>
    <div class= "form-group">
      <%= f.label :start_time, t("missions.start_time") %>
      <%= f.date_select :start_time %>
      <%= f.time_select :start_time, :ignore_date => true, class: "form-control" %>
    </div>
    <div class= "form-group">
      <%= f.label :end_time, t("missions.end_time") %>
      <%= f.date_select :end_time %>
      <%= f.time_select :end_time, :ignore_date => true %>
    </div>
    <h3> <%= t("missions.tag") %> </h3>
    <%= f.fields_for :tags do |tag| %>
      <div class="row">
        <div class="col-10">
          <%= tag.label :name %>
          <%= tag.text_field :name, placeholder: t("missions.tag_name") %>
        </div>
      </div>
    <% end %>
    <%= f.submit t("missions.submit"), data: { disable_with: false }, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/missions/_tag_fields.html.erb
<div class="nested-fields row">
  <div class="col-10">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: t("missions.tag_name") %>
  </div>
  <div class="col-10">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: t("missions.tag_name") %>
  </div>
</div>

app/views/missions/edit.html.erb
<h1 class="text-center"> <%= t("missions.edit_mission") %> </h1>

<%= render "mission_form", mission: @mission %>

app/views/missions/index.html.erb
<%= flash[:overdue] %>
<%= flash[:urgent] %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to t("user.personal_info"), user_path(id: current_user.id), class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to t("user.log_out"), signout_path, class: "nav-link", method: "delete" %>
      </li>
      <% if current_user.role == "admin" %>
        <li class="nav-item active">
          <%= link_to t("user.user_control"), admin_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
      <%= search_form_for @q, html: { class: "form-inline my-2 my-lg-0"} do |f| %>
        <%= f.label :title_cont, t("missions.title") %>
        <%= f.search_field :title_cont, class: "form-control mr-sm-2" %>

        <%= f.label :status_cont, t("missions.status") %>
        <%= f.search_field :status_cont, class: "form-control mr-sm-2" %>

        <%= f.label :tags_name_cont, t("missions.tag") %>
        <%= f.search_field :tags_name_cont, class: "form-control mr-sm-2" %>

        <%= f.submit t("missions.search"), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
  </div>
</nav>




<h1 class="text-center"> <%= t("missions.mission_list") %> </h1>

<div class="text-center p-3">
  <%= link_to t("missions.add_mission"), new_mission_path, class: "btn btn-success" %>
</div>

<table class="table">
  <thead>
    <tr>
      <td> <%= t("missions.mission_name") %> </td>
      <td> <%= t("missions.status") %> </td>
      <td> <%= link_to t("missions.start_time"), { url: nil , order_by: "created_at"} %> </td>
      <td> <%= link_to t("missions.end_time"), { url: nil , order_by: "end_time"} %> </td>
      <td> <%= link_to t("missions.priority"), { url: nil , order_by: "priority"} %> </td>
      <td> <%= t("missions.category") %> </td>
      <td> <%= t("missions.tag") %> </td>
      <td> <%= t("missions.action") %> </td>
    </tr>
  </thead>
  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td> <%= mission.title %> </td>
        <td> <%= mission_status(mission) %> </td>
        <td> <%= mission.start_time.strftime("%m-%d %H:%M") %> </td>
        <td> <%= mission.end_time.strftime("%m-%d %H:%M") %> </td>
        <td> <%= mission_enum_name(mission, :priority) %> </td>
        <td> <%= mission_enum_name(mission, :category)  %> </td>
        <td> 
          <% if mission.tags.any? %>
            <% mission.tags.each do |tag| %>
              <span class="badge badge-secondary"> <%= tag.name %> </span>
            <% end %>
          <% end %> 
        </td>
        <td>
          <%= link_to t("missions.edit"), edit_mission_path(id: mission.id), class: "btn btn-success" %> 
          <%= link_to t("missions.delete"), mission_path(id: mission.id), method: "delete", data: { confirm: t("missions.confirm_delete") }, class: "btn btn-danger" %> 
        </td>
      </tr>
    <% end %>
    <%= paginate(@missions, theme: 'twitter-bootstrap-4') %>
  </tbody>



</table>

app/views/missions/new.html.erb
<h1 class="text-center"> <%= t("missions.create_mission") %> </h1>

<%= render "mission_form", mission: @mission %>